### ISSUE TITLE
bad abscissa axis in graphs

### ISSUE THREAD

**Issue by azlux** [WarenGonzaga/covid19-tracker-cli#24]
![image](https://user-images.githubusercontent.com/11210117/78155075-4ce31900-743d-11ea-87b5-7be6de32e4fb.png)

Number on left look not good.
Az

**Comment by WarenGonzaga** [comment]
Hi @azlux what do you mean by "bad abscissa axis in graphs" can you explain in detail? Let me know also your suggestion regarding this.

**Comment by azlux** [comment]
Look at the numbers, there are not good.

**Comment by WarenGonzaga** [comment]
@azlux got it... I understand the issue now it might the chart we are using or there is an issue with the API we will review this thank you for reporting.

**Comment by crudson** [comment]
The API data is fine. I think you were wanting to right justify the labels but in doing this are just showing the last four digits. In `lib/cli/chart` instead of `('    ' + x.toFixed(0)).slice(-'    '.length)` first get the max value length with something like `Object.values(data.timeline[type].reduce((a,c) => Math.max(a, c.toFixed().length), 0)` then padStart() with this length when creating the labels.

**Comment by crudson** [comment]
![Screenshot_20200401_150103](https://user-images.githubusercontent.com/177683/78190831-a2adc600-7429-11ea-8b9f-b90ee03fe3cc.png)

See fixed axis as per suggested change in previous comment. I can do a pull req if you want.

**Comment by ianvizarra** [comment]
Hi @crudson Yes, please create PR to the `dev` branch. Thanks!

**Comment by ianvizarra** [comment]
Hi @azlux This is fixed #28  

Thanks @crudson
